### PR TITLE
feat(types)!: proper type exportation using `typescript`'s native exportation 

### PR DESCRIPTION
**Pull request by AceLikesGhosts**
Typescript natively supports exporting the required types, as seen in the [declaration]() configuration option.

This pull request modifies the tsconfig to use the declaration field in order to export the needed types, instead of copying a set of types. This allows the project to be future proofed alongside no longer needing an extra file in the Git repository.

This pull request does the following:

* Enables the `declaration` configuration option in the `tsconfig.json`
* Points the `types` field of the `package.json` to the respective folder that Typescript exports the types to (`./types`)
* Inline's the old `oauthDef.d.ts` file, and completely removes it
* Updates the gitignore to add the `types` folder, as it is generated on build.
* Removes the unneeded `cp` involving the now deleted `oauthDef.d.ts`

### CODE REVIEW

**Comment by AceLikesGhosts** [comment]
overstepping this PR in regards as to what it's intended to do, but why are is there not a `tsc` github workflow on this repo? 😭

**Comment by AceLikesGhosts** [comment]
Replying again to bump this. :(

**Comment by iSlammedMyKindle** [comment]
Sorry; I've been heavily busy with other things. I've been distant coding this item in favor of evolving other things surrounding it

It's part of a decentralized framework I've been building that helps do things with my avatar and other future projects. When I get time I'll have a peek at what you made

**Comment by AceLikesGhosts** [comment]
Alright! Take your time. Just wanted to get this dumb chore out of the way to simplify this project. (:
(Edited in order to fix minor spelling mistake 💀)

**Comment by AceLikesGhosts** [comment]
😐

**Comment by AceLikesGhosts** [comment]
😑

**Comment by AceLikesGhosts** [comment]
14d, bump.

**Comment by AceLikesGhosts** [comment]
This PR has been open for a month. Any updates?

**Comment by iSlammedMyKindle** [comment]
I am back - didn't meant to cut you off like that, activity has been so high I haven't been able to keep up

Now that it's relaxed I'm ready to review it and respond to other comments

**Comment by iSlammedMyKindle** [comment]
Looks good! I'll go ahead and merge

**Pull request merged**
